### ISSUE TITLE
legacy: port `run_sql` to SQLAlchemy models

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-sequencegenerator#1]
- [ ] `invenio_sequencegenerator/backend.py:22:from invenio.legacy.dbquery import run_sql`
- [ ] `invenio_sequencegenerator/backend.py:50:        return run_sql("""SELECT seq_value FROM "seqSTORE"`
- [ ] `invenio_sequencegenerator/backend.py:63:        run_sql("""INSERT INTO "seqSTORE" (seq_name, seq_value)`
- [ ] `invenio_sequencegenerator/cnum.py:26:from invenio.legacy.dbquery import run_sql`
- [ ] `invenio_sequencegenerator/cnum.py:53:        return run_sql("""SELECT seq_value FROM "seqSTORE" WHERE seq_value`
- [ ] `invenio_sequencegenerator/cnum.py:107:    return run_sql("""select seq_value from "seqSTORE" where`
- [ ] `invenio_sequencegenerator/cnum.py:113:    return run_sql("""INSERT INTO "seqSTORE" (seq_name, seq_value)`
- [ ] `invenio_sequencegenerator/texkey.py:38:from invenio.legacy.dbquery import run_sql`
- [ ] `invenio_sequencegenerator/texkey.py:254:    while run_sql(sql, [task_id])[0][0] not in ('DONE', 'ACK', 'ACK DONE'):`

**Comment by omelkonian** [comment]
@jirikuncar  I think this issue is obsolete. Remove it?

**Comment by jiri** [comment]
Excuse me? 😃

**Comment by jirikuncar** [comment]
@omelkonian sure, we can close it.
